//! WM keybindings: intercept Mod-prefixed keys and dispatch them as
//! `vibeshellctl ipc <action>` rather than forwarding to the focused client.
//!
//! Under WM_BACKEND=sway, sway itself reads the bindings generated by
//! `crates/sway/src/bin/generate-bindings.rs` and dispatches; vibewm has no
//! such reader, so it carries its own table here.
//!
//! User config: `$XDG_CONFIG_HOME/vibeshell/keybinds.toml` (default
//! `~/.config/vibeshell/keybinds.toml`). Falls back to hardcoded defaults
//! (see `default_bindings`) if the file doesn't exist, fails to parse, or
//! contains zero bindings. Reload is wired to SIGHUP through
//! `common::spawn_reload_listener` — edit the config and `vibeshellctl
//! reload` picks up changes without a vibewm restart.
//!
//! Schema:
//!
//! ```toml
//! [[bindings]]
//! keysym = "space"
//! modifiers = ["super"]
//! action = "spawn launcher"
//!
//! [[bindings]]
//! keysym = "tab"
//! modifiers = ["super"]
//! action = "ipc cycle-cluster --direction forward"
//! ```
//!
//! `action` is split on whitespace. First token `"spawn"` runs the named
//! binary directly; otherwise the whole argv is forwarded to `vibeshellctl`.

use std::path::PathBuf;
use std::process::Command;
use std::sync::{OnceLock, RwLock};

use serde::Deserialize;
use smithay::input::keyboard::xkb::keysyms;
use smithay::input::keyboard::xkb::Keysym;
use smithay::input::keyboard::ModifiersState;

#[derive(Debug, Clone)]
struct Binding {
    keysym: Keysym,
    require_logo: bool,
    require_shift: bool,
    require_ctrl: bool,
    require_alt: bool,
    /// Argv after `vibeshellctl` (or the binary name when `argv[0] == "spawn"`).
    argv: Vec<String>,
}

static BINDINGS: OnceLock<RwLock<Vec<Binding>>> = OnceLock::new();

fn bindings_lock() -> &'static RwLock<Vec<Binding>> {
    BINDINGS.get_or_init(|| RwLock::new(default_bindings()))
}

/// Read the user's keybind config (if any) and replace the live binding
/// table. Falls back to hardcoded defaults if the file is missing, fails to
/// parse, or yields zero bindings.
pub fn reload_from_disk() {
    let path = config_path();
    let bindings = match std::fs::read_to_string(&path) {
        Ok(text) => match parse_toml(&text) {
            Ok(parsed) if !parsed.is_empty() => {
                tracing::info!(
                    path = %path.display(),
                    count = parsed.len(),
                    "vibewm: loaded keybindings from config"
                );
                parsed
            }
            Ok(_) => {
                tracing::warn!(
                    path = %path.display(),
                    "vibewm: keybind config has zero entries; using defaults"
                );
                default_bindings()
            }
            Err(e) => {
                tracing::warn!(
                    path = %path.display(),
                    error = ?e,
                    "vibewm: keybind config parse failed; using defaults"
                );
                default_bindings()
            }
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            tracing::debug!(
                path = %path.display(),
                "vibewm: no user keybind config; using defaults"
            );
            default_bindings()
        }
        Err(e) => {
            tracing::warn!(?e, path = %path.display(), "vibewm: keybind config read failed; using defaults");
            default_bindings()
        }
    };
    *bindings_lock().write().expect("bindings lock poisoned") = bindings;
}

/// Returns true if `keysym` matches a binding under the given modifier state
/// AND the binding has been dispatched. Bare keys (no modifiers) match only
/// if the binding requires no modifiers.
pub fn try_dispatch(modifiers: &ModifiersState, keysym: Keysym) -> bool {
    let guard = bindings_lock().read().expect("bindings lock poisoned");
    for binding in guard.iter() {
        if binding.keysym == keysym
            && binding.require_logo == modifiers.logo
            && binding.require_shift == modifiers.shift
            && binding.require_ctrl == modifiers.ctrl
            && binding.require_alt == modifiers.alt
        {
            tracing::info!(?keysym, argv = ?binding.argv, "vibewm: WM keybinding fired");
            spawn_action(&binding.argv);
            return true;
        }
    }
    false
}

fn spawn_action(argv: &[String]) {
    if argv.is_empty() {
        return;
    }
    // First arg "spawn" → run the named binary directly. Anything else →
    // forward to `vibeshellctl <argv>`.
    let mut cmd = if argv[0] == "spawn" && argv.len() >= 2 {
        let mut c = Command::new(&argv[1]);
        c.args(&argv[2..]);
        c
    } else {
        let mut c = Command::new("vibeshellctl");
        c.args(argv);
        c
    };
    if let Err(e) = cmd.spawn() {
        tracing::warn!(?e, ?argv, "vibewm: failed to spawn keybinding action");
    }
}

fn config_path() -> PathBuf {
    if let Ok(custom) = std::env::var("VIBESHELL_KEYBINDS") {
        return PathBuf::from(custom);
    }
    let base = std::env::var("XDG_CONFIG_HOME")
        .ok()
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var("HOME")
                .ok()
                .map(|h| PathBuf::from(h).join(".config"))
        })
        .unwrap_or_else(|| PathBuf::from("/etc"));
    base.join("vibeshell").join("keybinds.toml")
}

#[derive(Debug, Deserialize)]
struct ConfigFile {
    #[serde(default)]
    bindings: Vec<ConfigBinding>,
}

#[derive(Debug, Deserialize)]
struct ConfigBinding {
    keysym: String,
    #[serde(default)]
    modifiers: Vec<String>,
    action: String,
}

fn parse_toml(text: &str) -> Result<Vec<Binding>, String> {
    let parsed: ConfigFile = toml::from_str(text).map_err(|e| e.to_string())?;
    let mut out = Vec::with_capacity(parsed.bindings.len());
    for cb in parsed.bindings {
        out.push(parse_binding(cb)?);
    }
    Ok(out)
}

fn parse_binding(cb: ConfigBinding) -> Result<Binding, String> {
    let keysym = parse_keysym(&cb.keysym)?;
    let mut require_logo = false;
    let mut require_shift = false;
    let mut require_ctrl = false;
    let mut require_alt = false;
    for m in &cb.modifiers {
        match m.to_ascii_lowercase().as_str() {
            "super" | "logo" | "mod4" | "win" => require_logo = true,
            "shift" => require_shift = true,
            "ctrl" | "control" => require_ctrl = true,
            "alt" | "mod1" => require_alt = true,
            other => {
                return Err(format!(
                    "unknown modifier `{other}` (expected super/shift/ctrl/alt)"
                ))
            }
        }
    }
    let argv: Vec<String> = cb.action.split_whitespace().map(|s| s.to_owned()).collect();
    if argv.is_empty() {
        return Err("action must not be empty".into());
    }
    Ok(Binding {
        keysym,
        require_logo,
        require_shift,
        require_ctrl,
        require_alt,
        argv,
    })
}

fn parse_keysym(name: &str) -> Result<Keysym, String> {
    let sym = smithay::input::keyboard::xkb::keysym_from_name(
        name,
        smithay::input::keyboard::xkb::KEYSYM_CASE_INSENSITIVE,
    );
    if sym.raw() == keysyms::KEY_NoSymbol {
        return Err(format!("unknown keysym `{name}`"));
    }
    Ok(sym)
}

/// Hardcoded defaults — used when no user config exists or it fails to load.
/// Mirrors the must-have entries in
/// `crates/sway/src/bin/generate-bindings.rs`.
fn default_bindings() -> Vec<Binding> {
    fn b(keysym: u32, require_shift: bool, argv: &[&str]) -> Binding {
        Binding {
            keysym: Keysym::new(keysym),
            require_logo: true,
            require_shift,
            require_ctrl: false,
            require_alt: false,
            argv: argv.iter().map(|s| (*s).to_owned()).collect(),
        }
    }
    vec![
        b(keysyms::KEY_space, false, &["spawn", "launcher"]),
        b(keysyms::KEY_slash, false, &["spawn", "cheatsheet"]),
        b(
            keysyms::KEY_Tab,
            false,
            &["ipc", "cycle-cluster", "--direction", "forward"],
        ),
        b(
            keysyms::KEY_Tab,
            true,
            &["ipc", "cycle-cluster", "--direction", "backward"],
        ),
        b(keysyms::KEY_equal, false, &["ipc", "zoom-in-mode"]),
        b(keysyms::KEY_minus, false, &["ipc", "zoom-out-mode"]),
        b(keysyms::KEY_period, false, &["ipc", "cycle-strip-forward"]),
        b(keysyms::KEY_comma, false, &["ipc", "cycle-strip-backward"]),
        b(keysyms::KEY_e, true, &["logout"]),
        b(keysyms::KEY_r, true, &["reload"]),
        b(
            keysyms::KEY_m,
            true,
            &["ipc", "enter-keyboard-move-mode-selected"],
        ),
        b(
            keysyms::KEY_Up,
            true,
            &["ipc", "keyboard-move-by", "--dx", "0", "--dy", "-96"],
        ),
        b(
            keysyms::KEY_Down,
            true,
            &["ipc", "keyboard-move-by", "--dx", "0", "--dy", "96"],
        ),
        b(
            keysyms::KEY_Left,
            true,
            &["ipc", "keyboard-move-by", "--dx", "-96", "--dy", "0"],
        ),
        b(
            keysyms::KEY_Right,
            true,
            &["ipc", "keyboard-move-by", "--dx", "96", "--dy", "0"],
        ),
        b(keysyms::KEY_Return, true, &["ipc", "commit-keyboard-move"]),
        b(keysyms::KEY_Escape, true, &["ipc", "cancel-keyboard-move"]),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_have_seventeen_entries() {
        assert_eq!(default_bindings().len(), 17);
    }

    #[test]
    fn parse_minimal_binding() {
        let toml = r#"
            [[bindings]]
            keysym = "space"
            modifiers = ["super"]
            action = "spawn launcher"
        "#;
        let parsed = parse_toml(toml).expect("parse");
        assert_eq!(parsed.len(), 1);
        assert!(parsed[0].require_logo);
        assert!(!parsed[0].require_shift);
        assert_eq!(
            parsed[0].argv,
            vec!["spawn".to_owned(), "launcher".to_owned()]
        );
    }

    #[test]
    fn parse_combined_modifiers() {
        let toml = r#"
            [[bindings]]
            keysym = "Return"
            modifiers = ["super", "shift"]
            action = "ipc commit-keyboard-move"
        "#;
        let parsed = parse_toml(toml).expect("parse");
        assert!(parsed[0].require_logo);
        assert!(parsed[0].require_shift);
    }

    #[test]
    fn unknown_modifier_errors() {
        let toml = r#"
            [[bindings]]
            keysym = "a"
            modifiers = ["frob"]
            action = "ipc reload"
        "#;
        assert!(parse_toml(toml).is_err());
    }

    #[test]
    fn unknown_keysym_errors() {
        let toml = r#"
            [[bindings]]
            keysym = "definitely-not-a-key"
            modifiers = ["super"]
            action = "ipc reload"
        "#;
        assert!(parse_toml(toml).is_err());
    }

    #[test]
    fn empty_action_errors() {
        let toml = r#"
            [[bindings]]
            keysym = "space"
            modifiers = ["super"]
            action = "   "
        "#;
        assert!(parse_toml(toml).is_err());
    }

    #[test]
    fn config_path_honors_override() {
        // SAFETY: pre-test, single-threaded.
        std::env::set_var("VIBESHELL_KEYBINDS", "/tmp/test-keybinds.toml");
        assert_eq!(config_path(), PathBuf::from("/tmp/test-keybinds.toml"));
        std::env::remove_var("VIBESHELL_KEYBINDS");
    }
}
