//! WM keybindings: intercept Mod-prefixed keys and dispatch them as
//! `vibeshellctl ipc <action>` rather than forwarding to the focused client.
//!
//! Under WM_BACKEND=sway, sway itself reads the bindings generated by
//! `crates/sway/src/bin/generate-bindings.rs` and dispatches; vibewm has no
//! such reader, so the bindings live here as Rust constants for now.
//!
//! Mod = Super (Mod4) by default — matches the session script. Future config:
//! read from `~/.config/vibeshell/keybinds.toml`.

use std::process::Command;

use smithay::input::keyboard::xkb::keysyms;
use smithay::input::keyboard::xkb::Keysym;
use smithay::input::keyboard::ModifiersState;

/// What to run when a binding fires. Vec<&str> is the argv after `vibeshellctl`.
struct Binding {
    keysym: Keysym,
    require_shift: bool,
    /// `vibeshellctl <argv...>` (excluding "vibeshellctl" itself).
    argv: &'static [&'static str],
}

/// Hard-coded binding table. Mirrors the must-have entries in
/// `crates/sway/src/bin/generate-bindings.rs`. Each row triggers a
/// `vibeshellctl <argv>` subprocess. Order matters only for readability.
const BINDINGS: &[Binding] = &[
    // Launcher / cheatsheet — spawn the standalone binary directly. (Sway
    // mode toggles via swaymsg-kill-or-launch; vibewm doesn't have an
    // equivalent toggle yet, so plain spawn for now.)
    Binding {
        keysym: Keysym::new(keysyms::KEY_space),
        require_shift: false,
        argv: &["spawn", "launcher"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_slash),
        require_shift: false,
        argv: &["spawn", "cheatsheet"],
    },
    // Cluster cycling.
    Binding {
        keysym: Keysym::new(keysyms::KEY_Tab),
        require_shift: false,
        argv: &["ipc", "cycle-cluster", "--direction", "forward"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Tab),
        require_shift: true,
        argv: &["ipc", "cycle-cluster", "--direction", "backward"],
    },
    // Zoom mode in/out.
    Binding {
        keysym: Keysym::new(keysyms::KEY_equal),
        require_shift: false,
        argv: &["ipc", "zoom-in-mode"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_minus),
        require_shift: false,
        argv: &["ipc", "zoom-out-mode"],
    },
    // Context-strip cycling (within a Focus zoom level).
    Binding {
        keysym: Keysym::new(keysyms::KEY_period),
        require_shift: false,
        argv: &["ipc", "cycle-strip-forward"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_comma),
        require_shift: false,
        argv: &["ipc", "cycle-strip-backward"],
    },
    // Session control.
    Binding {
        keysym: Keysym::new(keysyms::KEY_e),
        require_shift: true,
        argv: &["logout"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_r),
        require_shift: true,
        argv: &["reload"],
    },
    // Keyboard move flow (Shift modifier required throughout).
    Binding {
        keysym: Keysym::new(keysyms::KEY_m),
        require_shift: true,
        argv: &["ipc", "enter-keyboard-move-mode-selected"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Up),
        require_shift: true,
        argv: &["ipc", "keyboard-move-by", "--dx", "0", "--dy", "-96"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Down),
        require_shift: true,
        argv: &["ipc", "keyboard-move-by", "--dx", "0", "--dy", "96"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Left),
        require_shift: true,
        argv: &["ipc", "keyboard-move-by", "--dx", "-96", "--dy", "0"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Right),
        require_shift: true,
        argv: &["ipc", "keyboard-move-by", "--dx", "96", "--dy", "0"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Return),
        require_shift: true,
        argv: &["ipc", "commit-keyboard-move"],
    },
    Binding {
        keysym: Keysym::new(keysyms::KEY_Escape),
        require_shift: true,
        argv: &["ipc", "cancel-keyboard-move"],
    },
];

/// Returns true if `keysym` matches a binding under the given modifier state
/// AND the binding has been dispatched. Mod4 (logo/Super) is required for any
/// match — bare keys always pass through to the focused client.
pub fn try_dispatch(modifiers: &ModifiersState, keysym: Keysym) -> bool {
    if !modifiers.logo {
        return false;
    }
    for binding in BINDINGS {
        if binding.keysym == keysym && binding.require_shift == modifiers.shift {
            tracing::info!(?keysym, argv = ?binding.argv, "vibewm: WM keybinding fired");
            spawn_action(binding.argv);
            return true;
        }
    }
    false
}

fn spawn_action(argv: &[&str]) {
    if argv.is_empty() {
        return;
    }
    // First arg can be a sentinel for "spawn binary directly" rather than
    // routing through vibeshellctl, e.g. `spawn launcher` runs the launcher
    // binary. Anything else is forwarded to vibeshellctl.
    let mut cmd = if argv[0] == "spawn" && argv.len() >= 2 {
        let mut c = Command::new(argv[1]);
        c.args(&argv[2..]);
        c
    } else {
        let mut c = Command::new("vibeshellctl");
        c.args(argv);
        c
    };
    if let Err(e) = cmd.spawn() {
        tracing::warn!(?e, ?argv, "vibewm: failed to spawn keybinding action");
    }
}
